export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const FETCH_CHARACTER_PENDING = 'FETCH_CHARACTER_PENDING';
export const FETCH_CHARACTER_ERROR = 'FETCH_CHARACTER_ERROR';

export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const SORT_CHARACTER = 'UPDATE_SORT';
export const SORT_CHARACTER_ERROR = 'SORT_CHARACTER_ERROR';

export const SEARCH_CHARACTERS = 'SEARCH_CHARACTERS';

